# -*- coding: utf-8 -*-
"""유효기간이 붙은 확인서를 찾아내는 스캐너.

만료된 확인서를 '보유'로 두면 43종 판정이 실제보다 후하게 나온다.
공급사 선언서에는 유효기간이 파일명에만 적힌 경우, 본문에만 있는 경우,
양쪽 다 없다가 개정판에서 새로 생긴 경우가 뒤섞여 있어 육안 점검으로는 놓치기 쉽다.

사용법
    python expiry_scan.py <추출텍스트폴더> [원료코드 ...]

    추출텍스트폴더 : extract_pdfs.py 가 만든 <코드>.txt 들이 있는 폴더
    원료코드       : 생략하면 폴더 전체를 훑는다

예시
    python extract_pdfs.py "...\\2차\\6105OO\\610586(...)" "%TEMP%\\qa_text\\610586.txt"
    python expiry_scan.py "%TEMP%\\qa_text"
    python expiry_scan.py "%TEMP%\\qa_text" 610022 610762

출력은 '후보'다. 반드시 원문을 열어 발행일과 기간을 직접 확인할 것.
"""
import io, os, re, sys, glob

sys.stdout.reconfigure(encoding='utf-8')

# 폐기 문서는 판정 근거가 아니므로 제외한다(폴더명으로 상태가 표시되어 있음)
DEP = re.compile(r'(사용\s*X|사용기한\s*만료|구자료|제조사변경전)')

# 본문에서 '기간이 정해진 선언'을 가리키는 표현들.
# 실제 확인된 사례에서 뽑았다 — 순서대로 검사해 첫 번째 일치를 보고한다.
BODY = [
    (re.compile(r'valid\s+for\s+(a\s+period\s+of\s+)?one\s+year', re.I), '1년 유효 조항'),
    (re.compile(r'valid\s+for\s+a\s+period\s+of\s+\d+\s+year', re.I), 'N년 유효 조항'),
    (re.compile(r'shall\s+be\s+valid\s+for\s+one\s+year', re.I), '1년 유효 조항'),
    (re.compile(r'valid\s+till\s*[:：]', re.I), 'Valid till 명시'),
    (re.compile(r'valid\s+(effective\s+)?(from|until|till)\s', re.I), '유효기간 명시'),
    (re.compile(r'Expiry\s*Date\s*[:：]', re.I), 'Expiry Date 항목'),
    (re.compile(r'Date\s+of\s+Expiry', re.I), 'Date of Expiry 항목'),
    (re.compile(r'Berlaku\s+sampai', re.I), '인니 할랄 유효기간'),
    (re.compile(r'new\s+application\s+is\s+required', re.I), '갱신 요구 문구'),
    (re.compile(r'유효기간|유효기한'), '국문 유효기간'),
]

# 본문에 안 걸려도 파일명에 기간 표기가 있으면 후보로 올린다
NAME = re.compile(r'(유효기간|until|untill|valid|expiry|만료|\d{4}\.\d{2}\.\d{2})', re.I)

# 만료 조항이 아닌데 걸리는 표현 — BASF 서식의 "개정판이 나올 때까지 유효" 등
BENIGN = re.compile(r'valid\s+until\s+superseded', re.I)


def split_docs(raw):
    """추출본을 (문서명, 본문) 목록으로 나눈다.

    구분자가 두 가지다 — 둘 다 받는다.
      · `@@FILE: 이름` 한 줄            (2차 폴더 일괄 추출본)
      · `====` 줄 사이의 `FILE: 이름`   (extract_pdfs.py 출력)
    한쪽만 알면 다른 형식에서 조용히 0건을 반환해 버려 더 위험하다.

    본문이 통째로 비어 있는 문서(스캔본 중 페이지 텍스트가 하나도 없는 것)도
    반드시 빈 본문으로 돌려준다. 예전에는 이런 문서를 건너뛰는 바람에
    '폴더에 60건인데 판독 대상은 51건'처럼 조용히 줄어들었고,
    빠진 쪽이 하필 만료 COA 같은 중요한 문서였다.
    """
    if '@@FILE: ' in raw:
        out = []
        for b in raw.split('@@FILE: '):
            if not b.strip():
                continue
            nl = b.index('\n')
            out.append((b[:nl].strip(), b[nl + 1:]))
        return out
    out, pending, body = [], None, []
    for p in re.split(r'^={20,}\s*$', raw, flags=re.M):
        m = re.match(r'FILE:\s*(.+)$', p.strip())
        if m and len(p.strip().splitlines()) == 1:
            if pending is not None:
                out.append((pending, ''.join(body)))
            pending, body = m.group(1).strip(), []
        elif pending is not None:
            body.append(p)
    if pending is not None:
        out.append((pending, ''.join(body)))
    return out


def scan_file(path):
    """파일 하나에서 (문서명, 사유) 후보 목록을 뽑는다."""
    out = []
    raw = io.open(path, encoding='utf-8', errors='replace').read()
    for name, body in split_docs(raw):
        if DEP.search(name):
            continue
        for pat, label in BODY:
            m = pat.search(body)
            if not m:
                continue
            seg = re.sub(r'\s+', ' ', body[m.start():m.start() + 130]).strip()
            if BENIGN.search(seg):
                label = '%s (만료 조항 아님 — 개정판까지 유효)' % label
            out.append((name.split('/')[-1], '%s → %s' % (label, seg[:110])))
            break
        else:
            if NAME.search(name):
                out.append((name.split('/')[-1], '(파일명에 기간 표기, 본문 미검출)'))
    return out


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    root = sys.argv[1]
    codes = sys.argv[2:]
    if not os.path.isdir(root):
        print('폴더가 없습니다: %s' % root)
        return 1

    paths = ([os.path.join(root, c + '.txt') for c in codes] if codes
             else sorted(glob.glob(os.path.join(root, '*.txt'))))
    total = 0
    for p in paths:
        if not os.path.exists(p):
            print('건너뜀(파일 없음): %s' % os.path.basename(p))
            continue
        rows = scan_file(p)
        if not rows:
            continue
        total += 1
        print('=' * 76)
        print(os.path.basename(p)[:-4])
        for nm, tag in rows:
            print('  · %s' % nm[:78])
            print('      %s' % tag)
    print()
    print('유효기간 관련 문구가 걸린 원료 %d건 — 원문 확인 필요' % total)
    return 0


def demo():
    """자체 점검 — 실제로 만났던 문장들이 제대로 분류되는지 본다."""
    import tempfile
    samples = [
        ('animal_testing.pdf',
         'This declaration is valid until receiving a revised version. '
         'In any case this statement shall be valid for one year after the date written above.'),
        ('vegan.pdf', 'Valid till : 31st December, 2024 Generated by : SA'),
        ('halal_id.pdf', 'Berlaku sampai dengan : SEPTEMBER 3 RD, 2028'),
        ('basf_comp.pdf', 'This document is valid until superseded by a later version.'),
        ('plain_spec.pdf', 'pH 4.00 ~ 6.00 Specific Gravity 1.001 ~ 1.030'),
        ('사용X/old_coa.pdf', 'Expiry Date: 07/05/2023'),
        ('scanned_coa(유효기간).pdf', ''),      # 스캔본 — 본문 텍스트가 하나도 없다
    ]
    body = ''.join('@@FILE: %s\n%s\n' % (n, t) for n, t in samples)
    bar = '=' * 60
    body2 = ''.join('%s\nFILE: %s\n%s\n%s\n' % (bar, n, bar, t) for n, t in samples)
    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, '999999.txt')
        io.open(p, 'w', encoding='utf-8').write(body)
        rows = dict(scan_file(p))
        io.open(p, 'w', encoding='utf-8').write(body2)
        rows2 = dict(scan_file(p))
    assert set(rows) == set(rows2), 'FILE: 형식 파싱 결과가 @@FILE: 과 다릅니다'
    # 본문이 빈 스캔본도 목록에서 사라지면 안 된다 — 파일명 근거로 후보에 올라와야 한다
    assert '(파일명에 기간 표기, 본문 미검출)' in rows['scanned_coa(유효기간).pdf']
    assert '1년 유효 조항' in rows['animal_testing.pdf']
    assert 'Valid till 명시' in rows['vegan.pdf']
    assert '인니 할랄 유효기간' in rows['halal_id.pdf']
    assert '만료 조항 아님' in rows['basf_comp.pdf']
    assert 'plain_spec.pdf' not in rows          # 기간 표현이 없으면 안 걸려야 한다
    assert 'old_coa.pdf' not in rows             # 폐기 폴더는 제외되어야 한다
    print('expiry_scan 자체 점검 통과')


if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] == '--demo':
        demo()
    else:
        sys.exit(main())
